name: integration

on: [push, pull_request]

jobs:
  integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: 
          - 2.7.18
          - 3.6.15
          - 3.9.17
        dirac_version:
          - v8.0.29
          - v8.1.0a20

    container: python:${{ matrix.python }}-slim

    steps:
      - uses: actions/checkout@v4
      - name: Retrieve the secret and decode it to a file
        env:
          HOSTCERT: ${{ secrets.HOSTCERT }}
          HOSTKEY: ${{ secrets.HOSTKEY }}
        run: |
          echo $PWD
          cd Pilot
          mkdir -p etc/grid-security
          echo $HOSTCERT > etc/grid-security/hostcert.pem
          echo $HOSTKEY > etc/grid-security/hostkey.pem
          chmod 400 etc/grid-security/hostcert.pem
          chmod 644 etc/grid-security/hostkey.pem
      - name: tests
        run: |
          echo $PWD
          cd Pilot
          cp ../tests/CI/pilot_oldSchema.json pilot.json
          sed -i "s/VAR_JENKINS_SITE/DIRAC.Jenkins.ch/g" pilot.json
          sed -i "s/VAR_JENKINS_CE/jenkins.cern.ch/g" pilot.json
          sed -i "s/VAR_JENKINS_QUEUE/jenkins-queue_not_important/g" pilot.json
          sed -i "s/VAR_DIRAC_VERSION/${{ matrix.dirac_version }}/g" pilot.json
          sed -i "s#VAR_CS#https://lbcertifdirac70.cern.ch:9135/Configuration/Server#g" pilot.json
          sed -i "s#VAR_USERDN#/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=alboyer/CN=819281/CN=Alexandre Franck Boyer#g" pilot.json
          sed -i "s#VAR_USERDN_GRIDPP#${DIRACUSERDN_GRIDPP}#g" pilot.json
          cat pilot.json
          python dirac-pilot.py -M 1 -S DIRAC-Certification -N jenkins.cern.ch -Q jenkins-queue_not_important -n DIRAC.Jenkins.ch --cert --certLocation=/__w/Pilot/Pilot/Pilot/etc/grid-security --debug
          cat pilot.cfg
